name: CI - PR
on: [push]
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Get latest commit
              uses: actions/checkout@v2
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1.1.0
            - run: npm install --only=prod

            - run: npm run build
            - run: npm test
              env:
                  CI: true
            - name: Cypress run
              uses: cypress-io/github-action@v1
              with:
                  browser: chrome
                  headless: true
                  start: npm run serve
